# Generated by Django 5.0.3 on 2024-07-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menhaqimda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='', verbose_name='media/')),
            ],
        ),
    ]
