# Generated by Django 5.0.3 on 2024-07-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menhaqimda',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
