# Generated by Django 5.0.3 on 2024-07-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_menhaqimda_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('lavozim', models.CharField(max_length=60)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
