# Generated by Django 5.0.3 on 2024-07-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='foiz',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nomi',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
