# Generated by Django 5.0.3 on 2024-07-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category1_category2_category3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category1',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
        migrations.DeleteModel(
            name='Category3',
        ),
    ]
