# Generated by Django 5.0.3 on 2024-07-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category1_category2_category3_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=80)),
                ('rasm', models.ImageField(upload_to='media/')),
                ('app', models.CharField(max_length=50)),
                ('imgname', models.CharField(max_length=70)),
            ],
        ),
    ]
