# Generated by Django 5.0.3 on 2024-08-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_rasm_digitalimg_img_remove_digitalimg_app_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
        migrations.DeleteModel(
            name='Category3',
        ),
        migrations.DeleteModel(
            name='DigitalImg',
        ),
        migrations.DeleteModel(
            name='Menhaqimda',
        ),
        migrations.DeleteModel(
            name='Nomi',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
