# Generated by Django 5.0.3 on 2024-08-15 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_zapal_delete_category_delete_category1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zapal',
            old_name='title',
            new_name='ism',
        ),
    ]
